[package]
name = "cargo_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pre-commit-hooks = "0.3.0"

[package.metadata.precommit]
fmt = "cargo fmt"
test = "cargo test"
